#!/usr/bin/env bash
# Electrotech production deploy script
# Runs on the CyberPanel server, triggered by GitHub Actions on push to main

set -euo pipefail

log() { printf '\n\033[1;36m==> %s\033[0m\n' "$*"; }

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$PROJECT_ROOT"

log "Deploying from $PROJECT_ROOT"
log "Current commit (before pull): $(git rev-parse --short HEAD 2>/dev/null || echo 'n/a')"

log "Enabling maintenance mode"
php artisan down --refresh=15 --retry=60 || true

# Ensure cleanup on any failure: always bring the app back up.
cleanup() {
  log "Disabling maintenance mode"
  php artisan up || true
}
trap cleanup EXIT

log "Fetching latest code from origin/main"
git fetch --all --prune
git reset --hard origin/main

log "Installing Composer dependencies (production)"
composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist

if [ -f package-lock.json ]; then
  log "Installing NPM dependencies"
  npm ci --no-audit --no-fund
  log "Building frontend assets"
  npm run build
fi

log "Running database migrations"
php artisan migrate --force

log "Syncing roles and permissions catalog"
php artisan db:seed --class=Database\\Seeders\\RoleAndPermissionSeeder --force

log "Seeding chart of accounts (only adds missing accounts; never overwrites admin edits)"
php artisan db:seed --class=Database\\Seeders\\ChartOfAccountsSeeder --force

# Financial-statement demo data, so the client evaluating the preview site sees
# the four statements populated exactly as they were reviewed locally — an
# empty income statement proves nothing about whether it works.
#
# Runs ONCE and then never again on its own. The seeder marks every journal
# entry it owns with a document_number prefix, so the presence of one marked
# entry means the data is already there. That guard matters because the seeder
# also writes opening balances onto balance-sheet accounts: re-running it after
# the accountant has started entering real figures would overwrite their work.
#
# To deliberately refresh it (after changing the demo figures), set
# SEED_DEMO_FINANCIALS=true in the server's .env for one deploy.
#
# The skip decision lives inside the seeder, not here: it owns the marker it
# checks for, and keeping the two together means the guard cannot drift away
# from the data it protects. Calling it on every deploy is therefore safe.
log "Seeding financial-statement demo data (skips itself if already present)"
php artisan db:seed --class=Database\\Seeders\\FinancialStatementsDemoSeeder --force

# The REST API documentation is generated by Scribe, which is a require-dev
# package — and this deploy installs with `--no-dev`. The docs therefore CANNOT
# be built here; they are generated locally with `php artisan scribe:generate`
# and committed under public/api/docs/.
#
# Verify rather than assume: without this check a developer who forgot to
# regenerate after adding endpoints ships a docs link that 404s, and nobody
# finds out until the mobile developer opens it.
log "Verifying committed API documentation"
if [ -f public/api/docs/index.html ]; then
  echo "    API docs present: $(wc -c < public/api/docs/index.html) bytes"
  if [ ! -f public/api/docs/openapi.yaml ]; then
    echo "    WARNING: openapi.yaml is missing — client code generation will not work."
  fi
else
  echo "    WARNING: public/api/docs/index.html is missing."
  echo "             Run 'php artisan scribe:generate' locally and commit public/api/docs/."
  echo "             Continuing: missing docs must not block a production deploy."
fi

log "Clearing old caches"
php artisan optimize:clear
php artisan filament:clear-cached-components || true
php artisan icons:clear || true

log "Rebuilding production caches"
php artisan config:cache
php artisan route:cache
php artisan view:cache
php artisan event:cache
php artisan filament:cache-components || true
php artisan icons:cache || true
php artisan optimize

log "Ensuring storage symlink exists"
# --force overwrites a stale or wrongly-typed `public/storage` (e.g. a
# leftover directory from a previous misconfigured deploy). Without it,
# storage:link would silently fail and uploaded attachments would 404.
php artisan storage:link --force || true

log "Fixing writable permissions on storage and bootstrap/cache"
chmod -R ug+rwX storage bootstrap/cache || true

log "Restarting queue workers"
php artisan queue:restart || true

# Expired API access tokens stay in `personal_access_tokens` forever unless
# pruned. They cannot authenticate anything (Sanctum checks `expires_at`), so
# this is hygiene rather than a security fix — but the table is on the hot path
# of every API request and should not grow without bound.
#
# Also scheduled daily in routes/console.php; running it here means a deploy
# cleans up even if the server's cron for `schedule:run` is not configured.
log "Pruning expired API tokens"
php artisan sanctum:prune-expired --hours=24 || true

# Refresh the topbar bell so it matches live pipeline state right after a
# deploy: raise a red alert for every Tender with no offer and every In-Hand
# with no SMB, and drop any that no longer apply. Idempotent and non-fatal.
log "Reconciling pipeline alerts (missing offer / SMB)"
php artisan sales:notify-incomplete-operations || true

log "Deploy finished at commit: $(git rev-parse --short HEAD)"
