<?php

declare(strict_types=1);

namespace App\Http\Controllers\Api\V1\Delivery;

use App\Http\Api\ApiQuery;
use App\Http\Controllers\Api\V1\ApiController;
use App\Http\Requests\Api\V1\Delivery\StoreDeliveryMinuteRequest;
use App\Http\Requests\Api\V1\Delivery\UpdateDeliveryMinuteRequest;
use App\Http\Resources\Api\V1\Delivery\DeliveryMinuteResource;
use App\Models\DeliveryMinute;
use App\Models\DeliveryVoucher;
use App\Services\DeliveryMinuteService;
use DomainException;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

/**
 * @group 26. Delivery minutes
 *
 * محضر التسليم — the record that a delivery was handed over, and the document
 * circulated to every department afterwards.
 *
 * A minute is always raised **from a delivery voucher** and inherits that
 * voucher's operation and customer. Sending them separately would allow a
 * minute naming a different customer from the delivery it records — a
 * contradiction nobody could resolve months later.
 *
 * `distribute` is the one state it has, and it is one-way and idempotent:
 * calling it twice does not send a second round of notifications. After
 * distribution the minute freezes, because every department is already
 * holding the copy that went out.
 */
class DeliveryMinuteController extends ApiController
{
    public function __construct(
        private readonly DeliveryMinuteService $minutes,
    ) {}

    /**
     * List delivery minutes
     *
     * @authenticated
     *
     * @queryParam page integer The page number. Example: 1
     * @queryParam per_page integer Rows per page, max 100. Example: 25
     * @queryParam search string Matches the minute number. Example: DM-2026
     * @queryParam filter[project] integer Operation id. Example: 4
     * @queryParam filter[customer] integer Customer id. Example: 7
     * @queryParam filter[delivery_voucher] integer Delivery voucher id. Example: 18
     * @queryParam filter[distributed] boolean Whether it has gone out to the departments. Example: false
     * @queryParam filter[minute_date] string Inclusive date range from,until. Example: 2026-01-01,2026-06-30
     * @queryParam sort string Allowed: minute_number, minute_date, created_at. Example: -minute_date
     * @queryParam include string Allowed: project, customer, deliveryVoucher. Example: project
     *
     * @response 200 scenario="Success" {"data":[{"id":6,"type":"delivery_minute","minute_number":"DM-202609-0002","distributed":false,"delivery_voucher_id":18}],"meta":{"request_id":"9f1c","api_version":"1","pagination":{"total":1,"count":1,"per_page":25,"current_page":1,"total_pages":1}},"links":{"first":"","prev":null,"next":null,"last":""}}
     */
    public function index(Request $request): JsonResponse
    {
        $this->authorize('viewAny', DeliveryMinute::class);

        $minutes = ApiQuery::for(DeliveryMinute::query(), $request)
            ->allowFilters([
                'project' => ApiQuery::exact('project_id'),
                'customer' => ApiQuery::exact('customer_id'),
                'delivery_voucher' => ApiQuery::exact('delivery_voucher_id'),
                'distributed' => fn ($query, $value) => filter_var($value, FILTER_VALIDATE_BOOL)
                    ? $query->whereNotNull('distributed_at')
                    : $query->whereNull('distributed_at'),
                'minute_date' => ApiQuery::dateBetween('minute_date'),
            ])
            ->allowSearch(['minute_number'])
            ->allowSorts(['minute_number', 'minute_date', 'created_at'])
            ->allowIncludes(['project', 'customer', 'deliveryVoucher'])
            ->defaultSort('-minute_date')
            ->paginate();

        return $this->respondPaginated(DeliveryMinuteResource::collection($minutes));
    }

    /**
     * Show a delivery minute
     *
     * @authenticated
     *
     * @urlParam delivery_minute integer required The minute id. Example: 6
     *
     * @response 200 scenario="Success" {"data":{"id":6,"type":"delivery_minute","minute_number":"DM-202609-0002","content":"Nine panels received in good order.","distributed":true,"distributed_at":"2026-09-12T16:00:00+00:00"},"meta":{"request_id":"9f1c","api_version":"1"}}
     */
    public function show(DeliveryMinute $deliveryMinute): JsonResponse
    {
        $this->authorize('view', $deliveryMinute);

        return $this->respond(new DeliveryMinuteResource($this->loaded($deliveryMinute)));
    }

    /**
     * Raise a minute from a delivery
     *
     * The operation and the customer come from the voucher. The number is
     * generated by the server.
     *
     * @authenticated
     *
     * @bodyParam delivery_voucher_id integer required The delivery being recorded. Example: 18
     * @bodyParam content string optional What was handed over and in what condition. Example: Nine panels received in good order.
     *
     * @response 201 scenario="Created" {"data":{"id":6,"type":"delivery_minute","minute_number":"DM-202609-0002","distributed":false},"meta":{"request_id":"9f1c","api_version":"1"}}
     */
    public function store(StoreDeliveryMinuteRequest $request): JsonResponse
    {
        $this->authorize('create', DeliveryMinute::class);

        $voucher = DeliveryVoucher::query()->findOrFail($request->integer('delivery_voucher_id'));

        // A minute belongs to an operation — `delivery_minutes.project_id` is
        // NOT NULL, and the minute is filed in the operation's folder and
        // circulated in its name. A voucher raised without one therefore
        // cannot produce a minute, and saying so is better than letting the
        // insert fail as a 500 the caller cannot act on.
        if ($voucher->project_id === null) {
            throw new DomainException(__('errors.api.delivery_minute_needs_operation', [
                'number' => $voucher->voucher_number,
            ]));
        }

        $minute = $this->minutes->generateFromDelivery($voucher, $request->input('content'));

        return $this->respondCreated(new DeliveryMinuteResource($this->loaded($minute)));
    }

    /**
     * Edit a minute
     *
     * Only before distribution — the policy gates on that, so a circulated
     * minute answers **403**.
     *
     * @authenticated
     *
     * @urlParam delivery_minute integer required The minute id. Example: 6
     *
     * @bodyParam content string optional Example: Nine panels received; one crate opened for inspection.
     * @bodyParam minute_date date optional Example: 2026-09-12
     *
     * @response 200 scenario="Updated" {"data":{"id":6,"type":"delivery_minute","content":"Nine panels received; one crate opened for inspection."},"meta":{"request_id":"9f1c","api_version":"1"}}
     */
    public function update(UpdateDeliveryMinuteRequest $request, DeliveryMinute $deliveryMinute): JsonResponse
    {
        $this->authorize('update', $deliveryMinute);

        $deliveryMinute->update($request->validated());

        return $this->respond(new DeliveryMinuteResource($this->loaded($deliveryMinute->fresh())));
    }

    /**
     * Distribute to all departments
     *
     * ارسالها لجميع الأقسام — stamps the minute as distributed and notifies
     * every configured department role.
     *
     * Idempotent: a retry after the first distribution is a silent success and
     * sends nothing again, which matters on a weak link where the client
     * cannot tell a lost response from a lost request.
     *
     * @authenticated
     *
     * @urlParam delivery_minute integer required The minute id. Example: 6
     *
     * @response 200 scenario="Distributed" {"data":{"id":6,"type":"delivery_minute","distributed":true,"distributed_at":"2026-09-12T16:00:00+00:00"},"meta":{"request_id":"9f1c","api_version":"1"}}
     */
    public function distribute(DeliveryMinute $deliveryMinute): JsonResponse
    {
        $this->authorize('distribute', $deliveryMinute);

        $this->minutes->distribute($deliveryMinute);

        return $this->respond(new DeliveryMinuteResource($this->loaded($deliveryMinute->fresh())));
    }

    /**
     * Delete a minute
     *
     * Only before distribution.
     *
     * @authenticated
     *
     * @urlParam delivery_minute integer required The minute id. Example: 6
     *
     * @response 204 scenario="Deleted" {}
     */
    public function destroy(DeliveryMinute $deliveryMinute): JsonResponse
    {
        $this->authorize('delete', $deliveryMinute);

        if ($deliveryMinute->isDistributed()) {
            throw new DomainException(__('errors.api.delivery_minute_distributed'));
        }

        $deliveryMinute->delete();

        return $this->respondNoContent();
    }

    private function loaded(DeliveryMinute $minute): DeliveryMinute
    {
        return $minute->load(['project', 'customer', 'deliveryVoucher']);
    }
}
