<?php

declare(strict_types=1);

namespace App\Http\Requests\Api\V1\Delivery;

use App\Models\DeliveryVoucher;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

/**
 * Raise a delivery voucher.
 *
 * The voucher starts as a **Draft** and its number is generated by the server.
 * Neither signature can be sent here: each has its own endpoint and its own
 * permission, and a voucher that could be created pre-approved would make the
 * dual-signature rule decorative.
 *
 * `status`, `total_value`, `invoiced_value` and `invoicing_status` are all
 * derived and equally absent.
 */
class StoreDeliveryVoucherRequest extends FormRequest
{
    public function authorize(): bool
    {
        return $this->user()?->can('create', DeliveryVoucher::class) ?? false;
    }

    public function rules(): array
    {
        return [
            'customer_id' => ['required', 'integer', Rule::exists('customers', 'id')->whereNull('deleted_at')],
            'project_id' => ['nullable', 'integer', Rule::exists('projects', 'id')->whereNull('deleted_at')],
            'supply_order_number' => ['nullable', 'string', 'max:255'],
            'voucher_date' => ['nullable', 'date'],

            'plates_count' => ['nullable', 'integer', 'min:0'],
            'protection_degree' => ['nullable', 'string', 'max:255'],
            'insulation_voltage' => ['nullable', 'string', 'max:255'],
            'notes' => ['nullable', 'string', 'max:5000'],

            'lines' => ['nullable', 'array', 'max:500'],
            'lines.*.item_id' => ['required', 'integer', Rule::exists('items', 'id')->whereNull('deleted_at')],
            'lines.*.quantity' => ['required', 'numeric', 'gt:0'],
            'lines.*.unit_cost' => ['nullable', 'numeric', 'min:0'],
        ];
    }
}
