<?php

declare(strict_types=1);

namespace App\Http\Requests\Api\V1\Finance;

use App\Enums\DocumentType;
use App\Models\JournalEntry;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

/**
 * Open a draft journal entry.
 *
 * The entry number, the continuous serial and the per-type document number are
 * all generated by the server. `status` is absent: an entry reaches the books
 * through `post`, which is where the double-entry rule is enforced.
 *
 * Lines may be sent with the entry or written afterwards with
 * `PUT /journal-entries/{id}/lines`. They are given as two columns — مدين and
 * دائن — rather than as rows each carrying a direction, because that is how an
 * accountant writes an entry and the direction is then never a per-row
 * mistake.
 */
class StoreJournalEntryRequest extends FormRequest
{
    public function authorize(): bool
    {
        return $this->user()?->can('create', JournalEntry::class) ?? false;
    }

    public function rules(): array
    {
        return array_merge([
            'document_type' => ['required', Rule::enum(DocumentType::class)],
            'entry_date' => ['nullable', 'date'],
            'description' => ['nullable', 'string', 'max:5000'],
            'currency' => ['nullable', 'string', 'size:3'],
            'notes' => ['nullable', 'string', 'max:5000'],
        ], self::lineRules());
    }

    /**
     * Shared with ReplaceJournalEntryLinesRequest so the two shapes cannot
     * drift apart.
     *
     * @return array<string, array<int, mixed>>
     */
    public static function lineRules(): array
    {
        $rules = [];

        foreach (['debit_lines', 'credit_lines'] as $side) {
            $rules[$side] = ['nullable', 'array', 'max:200'];
            $rules["{$side}.*.id"] = ['nullable', 'integer'];
            // Nullable, not required: a client sends the empty row a form
            // always carries at the bottom, and the service drops any row with
            // no account. Rejecting it here would make the obvious payload a
            // validation error for no gain.
            $rules["{$side}.*.account_id"] = [
                'nullable',
                'integer',
                Rule::exists('accounts', 'id')->whereNull('deleted_at'),
            ];
            $rules["{$side}.*.project_id"] = [
                'nullable',
                'integer',
                Rule::exists('projects', 'id')->whereNull('deleted_at'),
            ];
            $rules["{$side}.*.amount"] = ['required', 'numeric', 'min:0'];
            $rules["{$side}.*.line_notes"] = ['nullable', 'string', 'max:1000'];
        }

        return $rules;
    }
}
