<?php

declare(strict_types=1);

namespace App\Http\Api;

use Illuminate\Contracts\Pagination\LengthAwarePaginator;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Resources\Json\JsonResource;
use Illuminate\Http\Resources\Json\ResourceCollection;
use Illuminate\Support\Facades\Request;

/**
 * The single place where an API response body is shaped.
 *
 * Every controller, and the exception renderer, funnel through here so the
 * envelope documented in API_Development_Plan.md §3.2/§3.3 is produced in
 * exactly one place. If a response somewhere in the app does not match the
 * contract, this class is the only file that needs to change.
 */
final class ApiResponse
{
    /**
     * A single resource. `$resource` may be a JsonResource, an array, or null.
     */
    public static function item(JsonResource|array|null $resource, int $status = 200, array $headers = []): JsonResponse
    {
        return response()->json([
            'data' => $resource instanceof JsonResource
                ? $resource->resolve(Request::instance())
                : $resource,
            'meta' => self::meta(),
        ], $status, $headers);
    }

    /**
     * A paginated collection. Emits `data`, `meta.pagination` and `links`.
     *
     * The paginator must already have been run through a resource collection
     * (or carry plain arrays) — we only read its items and page metadata here.
     */
    public static function paginated(ResourceCollection|LengthAwarePaginator $collection, int $status = 200): JsonResponse
    {
        $paginator = $collection instanceof ResourceCollection
            ? $collection->resource
            : $collection;

        if (! $paginator instanceof LengthAwarePaginator) {
            // Defensive: an unpaginated collection would silently return every
            // row. Fail loudly in development rather than ship an endpoint that
            // dumps the whole table over a mobile connection.
            throw new \LogicException('ApiResponse::paginated() requires a LengthAwarePaginator.');
        }

        $items = $collection instanceof ResourceCollection
            ? $collection->resolve(Request::instance())
            : $paginator->items();

        return response()->json([
            'data' => $items,
            'meta' => self::meta([
                'pagination' => [
                    'total' => $paginator->total(),
                    'count' => count($items),
                    'per_page' => $paginator->perPage(),
                    'current_page' => $paginator->currentPage(),
                    'total_pages' => $paginator->lastPage(),
                ],
            ]),
            'links' => [
                'first' => $paginator->url(1),
                'prev' => $paginator->previousPageUrl(),
                'next' => $paginator->nextPageUrl(),
                'last' => $paginator->url($paginator->lastPage()),
            ],
        ], $status);
    }

    /**
     * A collection that is genuinely bounded and small — enum catalogs, the
     * permission list, a user's active devices. Still wrapped in `data` so the
     * client never has to special-case a bare array.
     */
    public static function collection(array $items, int $status = 200): JsonResponse
    {
        return response()->json([
            'data' => $items,
            'meta' => self::meta(['count' => count($items)]),
        ], $status);
    }

    /**
     * 204 with a genuinely empty body. Used by DELETE and revoke-style actions.
     */
    public static function noContent(): JsonResponse
    {
        return response()->json(null, 204);
    }

    /**
     * The error envelope. `$details` is omitted entirely when empty rather than
     * emitted as `null`, so the client can rely on `isset(error.details)`.
     */
    public static function error(
        string $code,
        string $message,
        int $status,
        array $details = [],
        array $headers = [],
    ): JsonResponse {
        $error = [
            'code' => $code,
            'message' => $message,
        ];

        if ($details !== []) {
            $error['details'] = $details;
        }

        return response()->json([
            'error' => $error,
            'meta' => self::meta(),
        ], $status, $headers);
    }

    /**
     * Metadata attached to every response.
     *
     * `request_id` is generated by ApiRequestId middleware and echoed in the
     * `X-Request-Id` header too. It is the correlation handle a field bug
     * report needs, since APP_DEBUG is off in production.
     */
    private static function meta(array $extra = []): array
    {
        return array_merge([
            'request_id' => ApiRequestId::current(),
            'api_version' => (string) config('api.version'),
        ], $extra);
    }
}
